spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main_db
    username: deltauser
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Changed from create-drop to update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

jwt:
  secret: 3cfa76ef9db97e987c24a1c6b76c35e5a1f2b9c8d4e6f7a8a0e4d1e2f3a4b5c6
  expiration: 360000

# Optional: Logging configuration
logging:
  level:
    com.example.realtimechatapp: DEBUG